python/Flask/app/models.py
from . import db

class UserInput(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.String(200), nullable=False)

    def __repr__(self):
        return f"UserInput('{self.content}')"

class Book(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200), nullable=False)
    authors = db.Column(db.String(200), nullable=False)
    publisher = db.Column(db.String(200), nullable=False)
    published_date = db.Column(db.String(20), nullable=False)
    description = db.Column(db.Text, nullable=False)
    page_count = db.Column(db.Integer, nullable=False)
    main_category = db.Column(db.String(200), nullable=False)
    location = db.Column(db.String(50), nullable=True)

    def __repr__(self):
        return f"<Book {self.title}>"

python/Flask/app/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

db = SQLAlchemy()
migrate = Migrate()

data_dir = os.path.join(os.getcwd(), 'data')
if not os.path.exists(data_dir):
	os.makedirs(data_dir)

def create_app(): 
	catalogue = Flask(__name__)
	
	catalogue.config.from_object('config.Config')

#	catalogue.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(data_dir, 'site.db')
#	catalogue.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

	# Debug prints to verify environment variables
	print(f"SECRET_KEY: {catalogue.config['SECRET_KEY']}")
	print(f"SQLALCHEMY_DATABASE_URI: {catalogue.config['SQLALCHEMY_DATABASE_URI']}")
	
	db.init_app(catalogue)
	migrate.init_app(catalogue, db)	

	from . import routes
	catalogue.register_blueprint(routes.catalogue)

	return catalogue

python/Flask/app/routes.py
import os
import requests
from flask import Flask, Blueprint, render_template, url_for, request, redirect, flash, current_app
from .models import Book
from . import db


catalogue = Blueprint('main', __name__)

@catalogue.route('/')
def index():
        return render_template('index.html')

@catalogue.route('/second_page')
def second_page():
        records = Book.query.all()
        return render_template('second_page.html', records=records)

@catalogue.route('/save_input', methods=['POST'])
def save_input():
	user_input_content = request.form['user_input']
	if not user_input_content.strip():
		return redirect(url_for('main.index'))
	user_input = Book(content=user_input_content)
	db.session.add(user_input)
	db.session.commit()
	return redirect(url_for('main.index'))

@catalogue.route('/add_book', methods=['GET', 'POST'])
def add_book():
    print("add_book route called")  # Debug print statement
    if request.method == 'POST':
        print("POST request received")  # Debug print statement
        isbn = request.form['isbn']
        print(f"Received ISBN: {isbn}")  # Debug print statement
        api_key = current_app.config['GOOGLE_BOOKS_API_KEY']
        url = f'https://www.googleapis.com/books/v1/volumes?q=isbn:{isbn}&key={api_key}'
        print(f"URL: {url}")  # Debug print statement
        response = requests.get(url)
        print(f"Response status code: {response.status_code}")  # Debug print statement

        if response.status_code == 200:
            book_data = response.json()

            if 'items' in book_data:
                book_info = book_data['items'][0]['volumeInfo']
                title = book_info.get('title', 'N/A')
                authors = ', '.join(book_info.get('authors', []))
                publisher = book_info.get('publisher', 'N/A')
                published_date = book_info.get('publishedDate', 'N/A')
                description = book_info.get('description', 'N/A')
                page_count = book_info.get('page_count', 0)
                main_category = ', '.join(book_info.get('categories', []))
                location = 'shelf'

                # Save book info to the database
                new_book = Book(
                    title=title,
                    authors=authors,
                    publisher=publisher,
                    published_date=published_date,
                    description=description, 
                    page_count = page_count, 
                    main_category = main_category, 
                    location = location

                )
                db.session.add(new_book)
                db.session.commit()
                flash(f'Book "{title}" by {authors} added successfully.', 'success')
            else:
                flash('No book found with that ISBN', 'danger')
        else:
            flash('Error fetching book data', 'danger')
    return render_template('add_book.html')

python/Flask/app/templates/add_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Catalogue</title>
    <!-- Use this line for prod -->
   <!-- <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}"> -->
    <!-- Use this line for dev -->
     <link rel="stylesheet" href="../static/css/bootstrap.css">
</head>
<body data-bs-theme="light">

<!--navbar-->

    <nav class="navbar navbar-expand-lg bg-body-tertiary rounded">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.index') }}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.second_page') }}">View All Books</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Add New Book</a>
              </li>
              <!--
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
              </li>
              -->
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search All Books" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
    </nav>

<!--navbar endeth here-->





    <div class="row g-3">
        <h2>Add Book by ISBN</h2>
        <div class="col-sm-7">
        <form action="{{ url_for('main.add_book') }}" method="POST">
            <div class="form-group g-5 p-3">
                <input type="text" name="isbn" class="form-control" placeholder="Enter ISBN">
            </div>
            <button type="submit" class="btn btn-primary">Search</button>
        </form>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <div class="mt-3">
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">{{ message }}</div>
                    {% endfor %}
                </div>
            {% endif %}
        {% endwith %}
    </div>
   </div> 
<!-- Footer -->
<footer>
    <div class="text-end p-3 rounded" style="background-color: rgba(133, 133, 133, 0.2)">
        Greetings from Ohio!
      </div>
</footer>
<!-- Footer -->


<!-- jQuery, Popper.js, and Bootstrap JS via CDN -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<!--use this line for prod-->
<!-- <script src="{{ url_for('static', filename='js/bootstrap.js') }}"></script> -->
<!--use this line for dev-->
<script src="../static/js/bootstrap.js"></script>


</body>
</html>

python/Flask/app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Catalogue</title>
    <!-- Use this line for prod -->
   <!-- <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}"> -->
    <!-- Use this line for dev -->
     <link rel="stylesheet" href="../static/css/bootstrap.css">
</head>
<body data-bs-theme="light">

    <!--navbar-->

    <nav class="navbar navbar-expand-lg bg-body-tertiary rounded">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.second_page') }}">View All Books</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.add_book') }}">Add New Book</a>
              </li>
              <!--
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
              </li>
              -->
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search All Books" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
    </nav>


        <div class="container text-center p-3">
            <div class="row g-5 p-3">
              <div class="col">
                <div class="card">
                    <!-- <img src="..." class="card-img-top" alt="..."> -->
                     <div class="card-body">
                       <h5 class="card-title">Placeholder</h5>
                       <p class="card-text">To show that the page is working.</p>
                       <a href="#" class="btn btn-primary">Go somewhere</a>
                     </div>
                </div>
              </div>

              <div class="col">
                <div class="card">
                    <!-- <img src="..." class="card-img-top" alt="..."> -->
                     <div class="card-body">
                       <h5 class="card-title">Placeholder</h5>
                       <p class="card-text">To show that the page is working.</p>
                       <a href="#" class="btn btn-primary">Go somewhere</a>
                     </div>
                </div>
              </div>
            </div>

            <div class="row g-5 p-3 align-items-center">
              <div class="col">
                <div class="card">
                    <!-- <img src="..." class="card-img-top" alt="..."> -->
                     <div class="card-body">
                       <h5 class="card-title">Placeholder</h5>
                       <p class="card-text">To show that the page is working.</p>
                     </div>
                </div>
              </div>
              <div class="col">
                <div class="card">
                    <!-- <img src="..." class="card-img-top" alt="..."> -->
                     <div class="card-body">
                    <form action="{{ url_for('main.save_input') }}" method="POST">
                            <div class="form-group p-2">
                             <h5 class="card-title">UserInput</h5>
                                <input type="text" class="form-control" id="userInput" name="user_input">
                            </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                    </div>
                </div>
              </div>
              <div class="col">
                <div class="card">
                    <!-- <img src="..." class="card-img-top" alt="..."> -->
                     <div class="card-body">
                       <h5 class="card-title">Placeholder</h5>
                       <p class="card-text">To show that the page is working.</p>
                     </div>
                </div>
              </div>
            </div>

          </div>


    </div>

<!-- Footer -->
<footer>
        <div class="text-end p-3 rounded" style="background-color: rgba(133, 133, 133, 0.2)">
            Greetings from Ohio!
          </div>
  </footer>
  <!-- Footer -->


    <!-- jQuery, Popper.js, and Bootstrap JS via CDN -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
   <!--use this line for prod-->
    <!-- <script src="{{ url_for('static', filename='js/bootstrap.js') }}"></script> -->
   <!--use this line for dev-->
   <script src="../static/js/bootstrap.js"></script>


</body>
</html>

python/Flask/app/templates/second_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Catalogue</title>
    <!-- Use this line for prod -->
   <!-- <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}"> -->
    <!-- Use this line for dev -->
     <link rel="stylesheet" href="../static/css/bootstrap.css">
</head>
<body data-bs-theme="light">

<!--navbar-->

    <nav class="navbar navbar-expand-lg bg-body-tertiary rounded">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.index') }}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">View All Books</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.add_book') }}">Add New Book</a>
              </li>
              <!--
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
              </li>
              -->
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search All Books" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
    </nav>

<!--navbar endeth here-->

    <h1>Book List</h1>

  <!--sample  
    <ul>
        {% for book in records %}
        <li>
            <strong>Title:</strong> {{ book.title }}<br>
            <strong>Authors:</strong> {{ book.authors }}<br>
            <strong>Publisher:</strong> {{ book.publisher }}<br>
            <strong>Published Date:</strong> {{ book.published_date }}<br>
            <strong>Description:</strong> {{ book.description }}<br>
            <strong>Page Count:</strong> {{ book.page_count }}<br>
            <strong>Main Category:</strong> {{ book.main_category }}<br>
            <strong>Location:</strong> {{ book.location }}
        </li>
        {% endfor %}
    </ul>
 -->


    <div class="row g-5 p-3">
    {% for book in records %}
        <div class="col-sm-6 mb-3 mb-sm-0 w-25">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{{ book.title }}</h5>
              <p class="card-text">{{ book.authors }}</p>
              <a href="#" class="btn btn-primary">View Details</a>
            </div>
          </div>
        </div>
        {% endfor %}    
      </div>


<!-- Footer -->
    <footer>
        <div class="text-end p-3 rounded" style="background-color: rgba(133, 133, 133, 0.2)">
            Greetings from Ohio!
          </div>
    </footer>
<!-- Footer -->


    <!-- jQuery, Popper.js, and Bootstrap JS via CDN -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
   <!--use this line for prod-->
    <!-- <script src="{{ url_for('static', filename='js/bootstrap.js') }}"></script> -->
   <!--use this line for dev-->
   <script src="../static/js/bootstrap.js"></script>


</body>
</html>